---
# Creates a user on InfluxDB
#
# Expected, that following variables are populated:
# influxdb_hostname
# influxdb_admin_user_name
# influxdb_admin_user_password
# influxdb_enable_ssl
# influxdb_validate_cert
#
# influxdb_user_name
# influxdb_user_password
# influxdb_user_grants

- import_playbook: flush_jumphost_key.yaml

- name: Create user
  hosts: influxdb
  tasks:
    - import_role:
        name: opentelekomcloud_infra.influxdb
        tasks_from: create_user.yaml
