---
# Enable certbot on the target machine to generate certificates
#
# Note: for certbot_create_mode: webroot webserver need to be deployed first

- import_playbook: flush_jumphost_key.yaml

- hosts: all
  gather_facts: true
  vars:
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_hour: "3"
    certbot_auto_renew_minute: "30"
    certbot_auto_renew_options: "--quiet --no-self-upgrade"
    certbot_create_if_missing: true

  roles:
    - role: opentelekomcloud_infra.certbot
      when: hostvars[inventory_hostname].certbot_certs is defined
