---
# Provision (create) Network/VPC, Security Group for Dashboard
#
# Vars:
# network_name (default apimon-otc-net)
# 

- name: Provision VPC
  hosts: os_infra
  tasks:
    - name: Create VPC
      include_role:
        name: opentelekomcloud.vpc
    - name: Create security groups
      include_role:
        name: opentelekomcloud.security_group
        apply:
          tags: sg
      vars:
        securitygroup_name: "{{ sg.name }}"
        rules: "{{ sg.rules }}"
        description: "{{ sg.descr }}"
      loop:
        - {name: "{{grafana_sg_name}}", rules: "{{grafana_sg_rules}}",
           descr: "Grafana SG for APIMon"}
        - {name: "{{influxdb_sg_name}}", rules: "{{influxdb_sg_rules}}",
           descr: "InfluxDB SG for APIMon"}
        - {name: "{{web_proxy_sg_name}}", rules: "{{web_proxy_sg_rules}}",
           descr: "Web proxy SG for APIMon"}
        - {name: "{{alerta_sg_name}}", rules: "{{alerta_sg_rules}}",
           descr: "Alerta SG for APIMon"}
      loop_control:
        loop_var: sg
