---
# Provision (create) Host for influxdb
#
# Vars:
# influxdb_host_image (default: Standard_Fedora_30_latest)
# influxdb_host_flavor (default: s2.xlarge.2)
# influxdb_host_name
# influxdb_host_availability_zone (default eu-de-03)
# influxdb_host_root_volume_size (default 12)
# influxdb_host_data_volume_size (default 100)
# influxdb_host_security_groups
# influxdb_host_network
# influxdb_host_key_name

- name: Provision influxdb
  hosts: os_infra
  tasks:
    - name: Create server
      include_role:
        name: opentelekomcloud_infra.influxdb
        tasks_from: provision_openstack.yaml
